n_households: 4
log_std_min: -20
log_std_max: 2
hidden_size: 128
cuda: true
q_lr: 0.0003
p_lr: 0.0003
buffer_size: 1000000.0
env_name: wealth_distribution
init_exploration_policy: gaussian
n_epochs: 1500
epoch_length: 500
update_cycles: 10
target_update_interval: 1
display_interval: 1
batch_size: 128
gamma: 0.975
tau: 0.005
eval_episodes: 10
init_exploration_steps: 1000
ppo_tau: 0.95
ppo_gamma: 0.99
eps: 1.0e-05
update_epoch: 20
clip: 0.1
vloss_coef: 0.5
ent_coef: 0.01
max_grad_norm: 0.5
update_freq: 2
initial_train: 100
noise_rate: 0.1
epsilon: 0.1
save_interval: 100
upload_freq: 10
local_training_epoch: 50
